const GET_ALL_PUBLIC_LISTS = "lists/GET_ALL_PUBLIC_LISTS";
const GET_ALL_PRIVATE_LISTS = "lists/GET_ALL_PRIVATE_LISTS";
const CREATE_LIST = "lists/CREATE_LIST";
const DELETE_LIST = "lists/DELETE_LIST";
const UPDATE_LIST = "lists/UPDATE_LIST";
const GET_LIST_BY_ID = "lists/GET_LIST_BY_ID";
const SEARCH_LISTS = "lists/SEARCH_LISTS";

export default {
  GET_ALL_PUBLIC_LISTS,
  GET_ALL_PRIVATE_LISTS,
  GET_LIST_BY_ID,
  CREATE_LIST,
  DELETE_LIST,
  UPDATE_LIST,
  SEARCH_LISTS
};
